version: 2

project_name: coresmd
before:
  hooks:
  - go install github.com/coredhcp/coredhcp/cmds/coredhcp-generator@latest
  - coredhcp-generator -t generator/coredhcp/coredhcp.go.template -f generator/coredhcp/plugins.txt github.com/openchami/coresmd/plugin/coredhcp/coresmd github.com/openchami/coresmd/plugin/coredhcp/bootloop -o build/coredhcp/coredhcp.go
  - go mod tidy

builds:
  # CoreDHCP build
  - id: coredhcp
    main: ./build/coredhcp/
    goos:  # CoreDHCP only supports linux
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
      - v1

    # If you want to build this locally, you can set the following environment variables:
    # export BUILD_HOST=$(hostname)
    # export GO_VERSION=$(go version | awk '{print $3}')
    # export BUILD_USER=$(whoami)
    ldflags:
      - "-s -w \
         -X github.com/openchami/coresmd/internal/version.GitCommit={{ .Commit }} \
         -X github.com/openchami/coresmd/internal/version.BuildTime={{ .Date }} \
         -X github.com/openchami/coresmd/internal/version.Version={{ .Version }} \
         -X github.com/openchami/coresmd/internal/version.GitBranch={{ .Branch }} \
         -X github.com/openchami/coresmd/internal/version.GitTag={{ .Tag }} \
         -X github.com/openchami/coresmd/internal/version.GitState={{ .GitTreeState }} \
         -X github.com/openchami/coresmd/internal/version.BuildHost={{ .Env.BUILD_HOST }} \
         -X github.com/openchami/coresmd/internal/version.GoVersion={{ .Env.GO_VERSION }} \
         -X github.com/openchami/coresmd/internal/version.BuildUser={{ .Env.BUILD_USER }} "
    binary: coredhcp
    env:
      # The bootloop plugin uses sqlite3 which requires CGO.
      - CGO_ENABLED=1
      - >-
        CC={{- if eq .Os "linux" -}}
            {{- if eq .Arch "amd64" -}}gcc{{- else -}}aarch64-linux-gnu-gcc{{- end -}}
        {{- end }}

  # CoreDNS build
  - id: coredns
    main: ./build/coredns/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
      - v1

    ldflags:
      - "-s -w \
         -X github.com/openchami/coresmd/internal/version.GitCommit={{ .Commit }} \
         -X github.com/openchami/coresmd/internal/version.BuildTime={{ .Date }} \
         -X github.com/openchami/coresmd/internal/version.Version={{ .Version }} \
         -X github.com/openchami/coresmd/internal/version.GitBranch={{ .Branch }} \
         -X github.com/openchami/coresmd/internal/version.GitTag={{ .Tag }} \
         -X github.com/openchami/coresmd/internal/version.GitState={{ .GitTreeState }} \
         -X github.com/openchami/coresmd/internal/version.BuildHost={{ .Env.BUILD_HOST }} \
         -X github.com/openchami/coresmd/internal/version.GoVersion={{ .Env.GO_VERSION }} \
         -X github.com/openchami/coresmd/internal/version.BuildUser={{ .Env.BUILD_USER }} "
    binary: coredns
    env:
      - CGO_ENABLED=1
      - >-
        CC={{- if eq .Os "linux" -}}
            {{- if eq .Arch "amd64" -}}gcc{{- else -}}aarch64-linux-gnu-gcc{{- end -}}
        {{- end }}

dockers:
  - image_templates:
      # For PR builds use custom tag from env, for releases use semantic versioning
      - &amd64_linux_image "ghcr.io/openchami/{{.ProjectName}}:{{ if eq .Env.IS_PR_BUILD \"true\" }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Tag }}{{ end }}-amd64"
      - "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-amd64{{ end }}"
      - "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64{{ end }}"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: amd64
    goamd64: v3
    extra_files:
      - LICENSE
      - README.md

  - image_templates:
      - &arm64v8_linux_image "ghcr.io/openchami/{{.ProjectName}}:{{ if eq .Env.IS_PR_BUILD \"true\" }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Tag }}{{ end }}-arm64"
      - "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-arm64{{ end }}"
      - "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-arm64{{ end }}"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - README.md
      - LICENSE
    goarch: arm64

docker_manifests:
  # For releases: latest + semantic versioning tags
  - name_template: "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:latest{{ end }}"
    skip_push: "{{ eq .Env.IS_PR_BUILD \"true\" }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image

  - name_template: "ghcr.io/openchami/{{.ProjectName}}:{{ if eq .Env.IS_PR_BUILD \"true\" }}{{ .Env.DOCKER_TAG }}{{ else }}{{ .Tag }}{{ end }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image

  - name_template: "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}{{ end }}"
    skip_push: "{{ eq .Env.IS_PR_BUILD \"true\" }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image

  - name_template: "{{ if ne .Env.IS_PR_BUILD \"true\" }}ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}{{ end }}"
    skip_push: "{{ eq .Env.IS_PR_BUILD \"true\" }}"
    image_templates:
      - *amd64_linux_image
      - *arm64v8_linux_image

release:
  github:
    owner: OpenCHAMI
    name: coresmd
  draft: true
  name_template: "v{{ .Version }}"
  prerelease: auto
  mode: replace
