# SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
# SPDX-License-Identifier: MIT

[Container]

# Volumes
Volume=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/root_ca/root_ca.crt:ro,Z

# Networks for the Container to use
Network=host
HttpProxy=false

# Capabilities
AddCapability=NET_ADMIN
AddCapability=NET_RAW
