# Example CoreDHCP configuration with CoreSMD plugin
# This configuration provides DHCP services for OpenCHAMI cluster components

# Server configuration
server4:
  # Listen on all interfaces, port 67
  - address: 0.0.0.0:67
  # Listen on specific interface (uncomment and modify as needed)
  # - address: 192.168.1.1:67

# DHCPv4 plugins
plugins4:
  # CoreSMD plugin for dynamic IP assignment
  - coresmd:
      # SMD API endpoint
      - "https://smd.cluster.local"
      # Boot script base URL for iPXE
      - "http://192.168.1.1"
      # CA certificate path (empty for no TLS verification)
      - ""
      # Cache duration
      - "30s"
      # Lease duration
      - "24h"
      # Single port mode
      - "false"

# Logging configuration
log:
  level: info
  format: text 