# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT

name: govulncheck
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  govulncheck:
    uses: OpenCHAMI/github-actions/.github/workflows/govulncheck.yml@c64b0b92899cdf2b24a5d6663d98db3ff37f8d84 # seantronsen/feat/add-missing-workflows
