# SPDX-FileCopyrightText: © 2024-2025 Triad National Security, LLC.
# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT

name: test-unit-go
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  check:
    uses: OpenCHAMI/github-actions/.github/workflows/test-unit-go.yml@0c9d3259ca2dcc8bb93508ab70b7245ff6575b25 # experimental: github-actions v4.0 pre-release (seantronsen/feat/workflow-ports)
    with:
      go-version-file: go.mod
      test-args: -v -covermode=atomic ./...
      coverage: true

  test-unit-go:
    if: ${{ always() }}
    needs: [check]
    runs-on: ubuntu-slim
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with: { jobs: "${{ toJSON(needs) }}" }
